// Your restored bookings - all data preserved
export const demoBookings = [
  {
    id: 1,
    jobNumber: "PHONE_TEST_FINAL_FK",
    date: "2025-01-09",
    time: "09:25",
    pickup: "to Northdown",
    destination: "to Northdown",
    customerName: "Mr Martin Booking",
    customerPhone: "+447890120658, +441622858998, +441474705123",
    customerAccount: "CabCo & Co",
    customerReference: "3728883",
    passengers: 2,
    luggage: 2,
    vehicleType: "Saloon",
    price: "132.30",
    driverNotes: "Vehicle: Saloon, Passengers: 2, Luggage: 2",
    status: "completed",
    distance: "Vehicle: Saloon, Passengers: 2, Luggage: 2",
    duration: "59 min",
    waypoints: 0,
    sentToAutocab: false,
    via1: null,
    via2: null,
    via3: null,
    via4: null,
    via5: null,
    mobilityAids: null,
    capabilities: null,
    driver: null,
    autocabBookingId: null,
    pickupNote: null,
    pickupCode: null,
    destinationNote: null,
    destinationCode: null,
    company: null,
    phone: null,
    requestedDrivers: null,
    account: "CabCo Assists",
    ourReference: null,
    priority: null,
    returnDate: null,
    returnTime: null,
    returnFlightInfo: null,
    estimatedPrice: "132.30",
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: 2,
    jobNumber: "PHONE_TEST_FINAL_FK",
    date: "2025-01-09",
    time: "09:25",
    pickup: "to Northdown",
    destination: "to Northdown",
    customerName: "Mr Martin Booking",
    customerPhone: "+447890120658, +441622858998, +441474705123",
    customerAccount: "CabCo & Co",
    customerReference: "3728883",
    passengers: 2,
    luggage: 2,
    vehicleType: "Saloon",
    price: "132.30",
    driverNotes: "Vehicle: Saloon, Passengers: 2, Luggage: 2",
    status: "pending",
    distance: "Vehicle: Saloon, Passengers: 2, Luggage: 2",
    duration: "59 min",
    waypoints: 0,
    sentToAutocab: false,
    via1: null,
    via2: null,
    via3: null,
    via4: null,
    via5: null,
    mobilityAids: null,
    capabilities: null,
    driver: null,
    autocabBookingId: null,
    pickupNote: null,
    pickupCode: null,
    destinationNote: null,
    destinationCode: null,
    company: null,
    phone: null,
    requestedDrivers: null,
    account: "CabCo Assists",
    ourReference: null,
    priority: null,
    returnDate: null,
    returnTime: null,
    returnFlightInfo: null,
    estimatedPrice: "132.30",
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: 3,
    jobNumber: "907250326",
    date: "2025-07-09",
    time: "09:00",
    pickup: "Cruise Terminal One, Kent, CT17 9DQ",
    destination: "12 Surrey, KT1 2JF",
    customerName: "Mrs Helen Sullivan, Mr Dennis Sullivan",
    customerPhone: "07719754068, 07736719090",
    customerAccount: "SGH-SAGA",
    customerReference: "907250326",
    passengers: 2,
    luggage: 3,
    vehicleType: "Estate/Small MPV",
    price: "186.48",
    driverNotes: "Vehicle: Estate/Small MPV, Passengers: 2, Luggage: 3, Flight/Ship: Spirit Of Adventure",
    status: "pending",
    distance: "73.9 mi",
    duration: "79 min",
    waypoints: 0,
    sentToAutocab: false,
    via1: null,
    via2: null,
    via3: null,
    via4: null,
    via5: null,
    mobilityAids: "None",
    capabilities: null,
    driver: null,
    autocabBookingId: null,
    pickupNote: null,
    pickupCode: null,
    destinationNote: null,
    destinationCode: null,
    company: null,
    phone: null,
    requestedDrivers: null,
    account: "SGH-SAGA",
    ourReference: null,
    priority: null,
    returnDate: null,
    returnTime: null,
    returnFlightInfo: null,
    estimatedPrice: "186.48",
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: 4,
    jobNumber: "907250327",
    date: "2025-07-09",
    time: "10:30",
    pickup: "Canterbury East Station, Canterbury, Kent CT1 1BB",
    destination: "Dover Priory Station, Dover, Kent CT16 1TZ",
    customerName: "Mr John Smith",
    customerPhone: "07123456789",
    customerAccount: "SGH-SAGA",
    customerReference: "907250327",
    passengers: 1,
    luggage: 2,
    vehicleType: "Saloon",
    price: "89.50",
    driverNotes: "Vehicle: Saloon, Passengers: 1, Luggage: 2",
    status: "pending",
    distance: "30.9 mi",
    duration: "46 min",
    waypoints: 0,
    sentToAutocab: false,
    via1: null,
    via2: null,
    via3: null,
    via4: null,
    via5: null,
    mobilityAids: null,
    capabilities: null,
    driver: null,
    autocabBookingId: null,
    pickupNote: null,
    pickupCode: null,
    destinationNote: null,
    destinationCode: null,
    company: null,
    phone: null,
    requestedDrivers: null,
    account: "SGH-SAGA",
    ourReference: null,
    priority: null,
    returnDate: null,
    returnTime: null,
    returnFlightInfo: null,
    estimatedPrice: "89.50",
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: 5,
    jobNumber: "907250204",
    date: "2025-07-09",
    time: "08:15",
    pickup: "Canterbury West Station, Canterbury, Kent CT2 8AN",
    destination: "Cruise Terminal One, Dover Western Docks, Dover, Kent CT17 9DQ",
    customerName: "Dr John Baum, Mrs Elsie Baum",
    customerPhone: "+447483218841, +441580893640",
    customerAccount: "SGH-SAGA",
    customerReference: "907250204",
    passengers: 2,
    luggage: 2,
    vehicleType: "Saloon",
    price: "113.40",
    driverNotes: "Vehicle type: Saloon, Passengers: 2, Luggage: 2",
    status: "pending",
    distance: "44.8 mi",
    duration: "59 min",
    waypoints: 0,
    sentToAutocab: true,
    autocabBookingId: 373220,
    via1: null,
    via2: null,
    via3: null,
    via4: null,
    via5: null,
    mobilityAids: null,
    capabilities: null,
    driver: null,
    pickupNote: null,
    pickupCode: null,
    destinationNote: null,
    destinationCode: null,
    company: null,
    phone: null,
    requestedDrivers: null,
    account: "SGH-SAGA",
    ourReference: null,
    priority: null,
    returnDate: null,
    returnTime: null,
    returnFlightInfo: null,
    estimatedPrice: "113.40",
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: 2,
    jobNumber: "PHONE_TEST_FINAL_FL",
    date: "2025-01-09",
    time: "09:25",
    pickup: "to Northdown",
    destination: "to Northdown",
    customerName: "Mr Martin Booking",
    customerPhone: "+447890120658, +441622858998, +441474705123",
    customerAccount: "CabCo & Co",
    customerReference: "3728884",
    passengers: 2,
    luggage: 2,
    vehicleType: "Saloon",
    price: "132.30",
    driverNotes: "Vehicle: Saloon, Passengers: 2, Luggage: 2",
    status: "completed",
    distance: "Vehicle: Saloon, Passengers: 2, Luggage: 2",
    duration: "59 min",
    waypoints: 0,
    sentToAutocab: true,
    via1: null,
    via2: null,
    via3: null,
    via4: null,
    via5: null,
    mobilityAids: null,
    capabilities: null,
    driver: null,
    autocabBookingId: null,
    pickupNote: null,
    pickupCode: null,
    destinationNote: null,
    destinationCode: null,
    company: null,
    phone: null,
    requestedDrivers: null,
    account: "CabCo Assists",
    ourReference: null,
    priority: null,
    returnDate: null,
    returnTime: null,
    returnFlightInfo: null,
    estimatedPrice: "132.30",
    createdAt: new Date(),
    updatedAt: new Date()
  }
];